# This is a basic workflow to help you get started with Actions

name: brane_compute

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
      
      # Brane installation
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Install brane CLI
        run: |
          echo "add docker permission"
          sudo groupadd docker
	  sudo usermod -aG docker $USER
	  newgrp docker
          echo "step1"
          git clone https://github.com/docker/buildx.git && cd buildx
	  make install
	  docker buildx install
	  docker buildx create --use
          echo "step2"
          sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
	  sudo chmod +x /usr/local/bin/docker-compose
          echo "step3"
	  cd ..
	  sudo cp ./brane /usr/local/bin/brane
          sudo chmod +x /usr/local/bin/brane
          echo "step4"
	  brane --help

      - name: Build the brane package
        run: |
          brane build ./container.yml
          brane list